openapi: 3.0.0
paths:
  /users:
    post:
      operationId: UsersController_create
      summary: Create a user
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserDto'
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
      tags:
        - users
    get:
      operationId: UsersController_getAll
      summary: Get all users
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
      tags:
        - users
  /auth/login:
    post:
      operationId: AuthController_login
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserDto'
      responses:
        '201':
          description: ''
      tags:
        - Auth
  /auth/registration:
    post:
      operationId: AuthController_registration
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserDto'
      responses:
        '201':
          description: ''
      tags:
        - Auth
  /auth/logout:
    post:
      operationId: AuthController_logout
      parameters: []
      responses:
        '201':
          description: ''
      tags:
        - Auth
  /auth/token:
    get:
      operationId: AuthController_getToken
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - Auth
info:
  title: Video-app
  description: REST API documentation
  version: 1.0.0
  contact: {}
tags: []
servers: []
components:
  schemas:
    CreateUserDto:
      type: object
      properties:
        email:
          type: string
          example: name@gmail.com
          description: E-mail
        password:
          type: string
          example: '123456789'
          description: Password
      required:
        - email
        - password
    User:
      type: object
      properties:
        id:
          type: number
          example: '1'
          description: id
        email:
          type: string
          example: name@gmail.com
          description: E-mail
      required:
        - id
        - email
